/* MENSAJES */
#define MSJ_BIENVENIDA "BIENVENIDO AL PROGRAMA DE MUESTREO"
#define MSJ_SELECCION_ESTADO "INGRESE EL NUMERO DE LA OPCION QUE DESEE:"
#define MSJ_TIEMP_INIC "INGRESE EL TIEMPO EN EL QUE DESEA INICIAR EL MUESTREO:"
#define MSJ_TIEMP_FINAL "INGRESE EL TIEMPO EN EL QUE DESEA FINALIZAR EL MUESTREO:"
#define MSJ_NUM_MUESTRAS "INGRESE LA CANTIDAD DE MUESTRAS QUE DESEA TOMAR:"
#define MSJ_AMPLITUD "INGRESE UN VALOR PARA LA AMPLITUD:"
#define MSJ_FRECUENCIA "INGRESE UN VALOR PARA LA FRECUENCIA:"
#define MSJ_ANG_INIC "INGRESE UN VALOR PARA EL ANGULO INICIAL:"
#define MSJ_PRECISION_DEC "INGRESE LA CANTRIDAD DE DECIMALES DE PRECISION DESEADA:"
#define MSJ_POS_INICIAL "INGRESE LA POSICION INCIAL:"
#define MSJ_VEL_INICIAL "INGRESE LA VELOCIDAD INCIAL:"
#define MSJ_ACELERACION "INGRESE LA ACELERACION:"
#define MSJ_VAR_A "INGRESE EL VALOR DE a:"
#define MSJ_VAR_B "INGRESE EL VALOR DE b:"
#define MSJ_TIEMP_INIC_X "INGRESE EL VALOR INICIAL PARA LA VARIABLE X:"
#define MSJ_TIEMP_INIC_Y "INGRESE EL VALOR INICIAL PARA LA VARIABLE Y:"
#define MSJ_TIEMP_FINAL_X "INGRESE EL VALOR FINAL PARA LA VARIABLE X:"
#define MSJ_TIEMP_FINAL_Y "INGRESE EL VALOR FINAL PARA LA VARIABLE Y:"


/* VALORES DEL MENU */
#define SELEC_SIN 1
#define SELEC_LOG 2
#define SELEC_LINEAL 3
#define SELEC_EXP 4
#define SELEC_HEAV 5
#define SELEC_MRUA 6
#define SELEC_PARAB 7
#define SELEC_SALIR 0  

/* VARIABLES */
#define PI 3.14
#define NOMBRE_VAR_1 	"x"
#define NOMBRE_VAR_2 	"y"
#define FUNC_1_VAR   	"f(x)"
#define FUNC_2_VAR		"f(x,y)"

/* MENSAJES DE ERROR */ 
#define ERR_INGRESO "LA OPCION INGRESADA NO ES CORRECTA."