/* MENSAJES */
# define MSJ_BIENVENIDA "BIENVENIDO AL PROGRAMA DE MUESTREO"
# define MSJ_SELECCION_ESTADO "INGRESE EL NUMERO DE LA OPCION QUE DESEE:"
# define MSJ_TIEMP_INIC "INGRESE EL TIEMPO EN EL QUE DESEA INICIAR EL MUESTREO:"
# define MSJ_TIEMP_FINAL "INGRESE EL TIEMPO EN EL QUE DESEA FINALIZAR EL MUESTREO:"
# define MSJ_NUM_MUESTRAS "INGRESE LA CANTIDAD DE MUESTRAS QUE DESEA TOMAR:"
# define MSJ_AMPLITUD "INGRESE UN VALOR PARA LA AMPLITUD:"
# define MSJ_FRECUENCIA "INGRESE UN VALOR PARA LA FRECUENCIA:"
# define MSJ_ANG_INIC "INGRESE UN VALOR PARA EL ANGULO INICIAL:"




/* VALORES DEL MENU */
# define SELEC_ENTRADA 0
# define SELEC_SIN 1
# define SELEC_LOG 2
# define SELEC_LINEAL 3
# define SELEC_EXP 4
# define SELEC_HEAV 5
# define SELEC_MRUA 6
# define SELEC_PARAB 7
# define SELEC_SALIR 'a'  

# define PI 3.14

/* MENSAJES DE ERROR */ 
# define ERR_INGRESO "LA OPCION INGRESADA NO ES CORRECTA."
